### ISSUE TITLE
Label text overflows when uploading multiple files in iOS Safari

### ISSUE THREAD

**Issue by alstr** [Johann-S/bs-custom-file-input#75]
I noticed when doing some testing that when using iOS Safari, if you upload multiple image files (which have pretty long names when stored in Photos), the text overflows the label and isn't hidden.

I propose something like:

```css
.custom-file-label {
    white-space: nowrap !important;
    overflow: hidden !important;
    text-overflow: ellipsis !important;
    padding-right: 25%;
}
```

The padding is optional but I think it looks better truncated with an ellipsis. This was the easiest way to achieve that.
